sdk:
  - any: ['packages/hms-video-web/**/*']
    all:
      [
        '!packages/hms-video-web/**/*.test.ts',
        '!packages/hms-video-web/**/*.spec.ts',
        '!packages/hms-video-web/scripts/*.js',
      ]

store:
  - any: ['packages/hms-video-store/**/*']
    all:
      [
        '!packages/hms-video-store/**/*.test.ts',
        '!packages/hms-video-store/**/*.spec.ts',
        '!packages/hms-video-store/scripts/*.js',
      ]

'sdk-test':
  - any: ['packages/hms-video-web/**/*.test.ts', 'packages/hms-video-web/**/*.spec.ts']

'store-test':
  - any: ['packages/hms-video-store/**/*.test.ts', 'packages/hms-video-store/**/*.spec.ts']

ci:
  - '.github/**'

'sdk-build':
  - 'packages/hms-video-web/scripts/*'

'store-build':
  - 'packages/hms-video-store/scripts/*'

documentation:
  - any: ['**/*.md', '**/*.mdx']
