version: 1
labels:
  - label: 'sdk'
    files:
      - 'packages/hms-video-web/**'

  - label: 'store'
    files:
      - 'packages/hms-video-store/**'

  - label: 'sdk-test'
    files:
      - 'packages/hms-video-web/**/*.(test|spec).ts'

  - label: 'store-test'
    files:
      - 'packages/hms-video-store/**/*.(test|spec).ts'
