test:
  - 'packages/hms-video-web/cypress/integration/gum.spec.ts'

build:
  - '**/scripts/*.js'

sdk:
  - any: ['packages/hms-video-web/**/*']
    all: ['!./packages/hms-video-web/scripts/*.js', '!./packages/hms-video-web/**/*.(test|spec).ts']

store:
  - any: ['packages/hms-video-store/**/*']
    all: ['!packages/hms-video-store/scripts', '!packages/hms-video-store/**/*.(test|spec).ts']

ci:
  - '.github/*'

docs:
  - '**/*.md'
