sdk:
  - any: ['packages/hms-video-web/**/*']
    all:
      [
        '!packages/hms-video-web/**/*.test.ts',
        '!packages/hms-video-web/**/*.spec.ts',
        '!packages/hms-video-web/scripts/*.js',
      ]

store:
  - any: ['packages/hms-video-store/**/*']
    all:
      [
        '!packages/hms-video-store/**/*.test.ts',
        '!packages/hms-video-store/**/*.spec.ts',
        '!packages/hms-video-store/scripts/*.js',
      ]
test:
  - any: ['**/*.test.ts', '**/*.spec.ts']

ci:
  - '.github/*'

build:
  - any: ['packages/*/scripts']

documentation:
  - '**/*.md'
