name: Publish alpha
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - 'README.MD'
      - '.gitignore'
      - 'package.json'
      - 'yarn.lock'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Update version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          npm version prerelease --preid=alpha 
          git push

      - name: Install packages
        run: yarn install

      - name: Test
        run: yarn test --ci --coverage

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: alpha
