name: Update Alpha Version
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Update version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          npm version prerelease --preid=alpha
          git add package.json
          git commit -m "chore: update version"
          git push
