
name: lint-test-build
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --ci --coverage
      - name: Build
        run: yarn build
