
name: lint-test-build
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --ci --coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build
