/**
 * @100mslive/hms-whiteboard
 * @version 0.2.0
 *
 * This package re-exports the whiteboard components from @100mslive/whiteboard-core
 * and provides integration with 100ms session store using proper gRPC-web protocol.
 */

// Import CSS for rollup to bundle
import './index.css';

// Export the backward-compatible Whiteboard component with session store integration
export { Whiteboard, type WhiteboardProps } from './Whiteboard';

// Re-export everything from the core whiteboard package (except Whiteboard to avoid conflict)
export {
  // Components (excluding Whiteboard)
  WhiteboardCanvas,
  Toolbar,
  PdfControls,
  RemoteCursors,
  CollaborationIndicator,
  type WhiteboardHandle,
  type WhiteboardImportData,
  type WhiteboardCanvasProps,
  type WhiteboardCanvasHandle,
  type ToolbarProps,
  type PdfControlsProps,
  type RemoteCursorsProps,
  type CollaborationIndicatorProps,
  // Hooks
  useWhiteboardState,
  useCanvasSize,
  usePdf,
  usePdfAnnotations,
  useCollaboration,
  useRemoteCursors,
  usePresence,
  useImage,
  useClipboard,
  useExport,
  useHMSWhiteboard,
  useHMSWhiteboardSync,
  type UseWhiteboardStateReturn,
  type CanvasSize,
  type UseCanvasSizeOptions,
  type PdfState,
  type UsePdfReturn,
  type PdfAnnotationLayerState,
  type UsePdfAnnotationsReturn,
  type UseCollaborationReturn,
  type RemoteCursorDisplay,
  type UseRemoteCursorsReturn,
  type PresenceUser,
  type UsePresenceReturn,
  type ImageImportState,
  type ImageImportOptions,
  type UseImageReturn,
  type ClipboardState,
  type ClipboardOptions,
  type ClipboardData,
  type UseClipboardReturn,
  type ExportState,
  type UseExportOptions,
  type UseExportReturn,
  type UseHMSWhiteboardConfig,
  type UseHMSWhiteboardResult,
  // State
  WhiteboardState,
  History,
  type WhiteboardStateData,
  type Command,
  createInitialState,
  AddElementCommand,
  RemoveElementsCommand,
  UpdateElementCommand,
  MoveElementsCommand,
  // Core
  Renderer,
  InputHandler,
  type RendererOptions,
  type InputCallbacks,
  type InputHandlerOptions,
  DEFAULT_RENDERER_OPTIONS,
  DEFAULT_INPUT_OPTIONS,
  // Tools
  BaseTool,
  SelectTool,
  PenTool,
  ShapeTool,
  LineTool,
  PanTool,
  EraserTool,
  ToolManager,
  type ToolContext,
  type AnnotationTarget,
  type ToolManagerConfig,
  type ShapeType,
  // Types
  type Point,
  type Vector,
  type Size,
  type BoundingBox,
  type Rect,
  type Transform,
  type Camera,
  type PathPoint,
  type ElementId,
  type ElementType,
  type BaseElement,
  type PathElement,
  type RectangleElement,
  type EllipseElement,
  type LineElement,
  type TextElement,
  type ImageElement,
  type PdfElement,
  type WhiteboardElement,
  type ToolType,
  type PointerInfo,
  type ToolState,
  type ToolOptions,
  type ToolHandlers,
  // Geometry utilities
  point,
  vector,
  boundingBox,
  rectFromBoundingBox,
  boundingBoxFromRect,
  IDENTITY_TRANSFORM,
  DEFAULT_CAMERA,
  // Element utilities
  generateElementId,
  createBaseElement,
  createPathElement,
  createRectangleElement,
  createEllipseElement,
  createLineElement,
  createImageElement,
  createPdfElement,
  getElementBoundingBox,
  isPointInElementBounds,
  // Tool defaults
  DEFAULT_TOOL_OPTIONS,
  // Sync / Collaboration
  LocalSyncProvider,
  WebSocketProvider,
  BroadcastProvider,
  HMSSessionStoreProvider,
  createHMSSessionStoreProvider,
  HMSSessionStore,
  calculateBackoff,
  decodeJWT,
  YjsDocument,
  CollaborationManager,
  type SyncProvider,
  type ConnectionState,
  type UserInfo,
  type RemoteCursor,
  type AwarenessState,
  type SyncEventType,
  type SyncEventListener,
  type SyncProviderConfig,
  type ElementChange,
  type SyncStats,
  type CollaborationConfig,
  type CollaborationState,
  type CollaborationStateListener,
  type YjsElementObserver,
  type HMSSessionStoreProviderConfig,
  type BackoffState,
  type SessionStoreCallbacks,
  type HMSSessionStoreConfig,
  // PDF
  PdfLoader,
  pdfLoader,
  type PdfPageInfo,
  type PdfDocumentInfo,
  type PdfMetadata,
  type PdfRenderOptions,
  type PdfRenderResult,
  DEFAULT_RENDER_OPTIONS,
  // Export
  exportToImage,
  exportToPng,
  exportToJpeg,
  exportToWebp,
  exportRegion,
  createThumbnail,
  exportToSvg,
  parseSvg,
  exportToPdf,
  exportToPdfVector,
  exportToJson,
  importFromJson,
  mergeElements,
  cloneElements,
  filterElements,
  calculateExportBounds,
  downloadBlob,
  downloadString,
  canvasToBlob,
  dataUrlToBlob,
  blobToDataUrl,
  generateFilename,
  type ExportFormat,
  type ImageExportOptions,
  type SvgExportOptions,
  type PdfExportOptions,
  type JsonExportOptions,
  type ExportResult,
  type WhiteboardDocument,
  DOCUMENT_VERSION,
  DEFAULT_IMAGE_EXPORT_OPTIONS,
  DEFAULT_SVG_EXPORT_OPTIONS,
  DEFAULT_PDF_EXPORT_OPTIONS,
  DEFAULT_JSON_EXPORT_OPTIONS,
  // Image utilities
  loadImage,
  loadImageFromFile,
  loadImageFromUrl,
  extractImageFromClipboard,
  extractImagesFromDrop,
  calculateFitDimensions,
  resizeImage,
  isDataUrl,
  isImageUrl,
  clearImageCache,
  getImageCacheStats,
  SUPPORTED_IMAGE_TYPES,
  type ImageInfo,
  type ImageLoadResult,
  // Annotation utilities
  isAnnotation,
  getAnnotationsForElement,
  getAnnotationsForPage,
  getAnnotationsByPage,
  toRelativePosition,
  toAbsolutePosition,
  scaleAnnotationPosition,
  isPointInPdfBounds,
  findPdfAtPoint,
  createAnnotationProps,
  getAnnotationIds,
  getVisibleAnnotationIds,
  calculateAnnotationMoves,
  type AnnotationInfo,
} from '@100mslive/whiteboard-core';

// Export our protobuf-ts based session store client
// This provides proper gRPC-web protocol support for 100ms session store
export { SessionStore } from './hooks/StoreClient';

// Export gRPC types for advanced usage
export { Value_Type } from './grpc/sessionstore';
export type {
  Value,
  GetRequest,
  GetResponse,
  SetRequest,
  SetResponse,
  DeleteRequest,
  DeleteResponse,
  ChangeStream,
  OpenRequest,
  CountRequest,
  CountResponse,
  Select,
} from './grpc/sessionstore';

// Export the protobuf-ts based StoreClient for direct usage
export { StoreClient as GrpcStoreClient } from './grpc/sessionstore.client';
