name: Apply label
on:
  pull_request:
    branches:
      - main

jobs:
  update-label:
    runs-on: ubuntu-latest
    outputs:
      sdk: ${{ steps.filter.outputs.sdk }}
      store: ${{ steps.filter.outputs.store }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            sdk:
              - 'packages/hms-video-web/src/**/!(*.test.ts)'
            store:
              - 'packages/hms-video-store/src/!(test)**/!(*.test.ts)'
            react-sdk:
              - 'packages/react-sdk/src/**'
            react-ui:
              - 'packages/react-ui/src/**'
            react-icons:
              - 'packages/react-icons/src/**'
            sdk-test: 
              - 'packages/hms-video-web/**/*.(test|spec).ts'
            store-test: 
              - 'packages/hms-video-store/**/*.(test|spec).ts'
            noise-suppression:
              - 'packages/hms-noise-suppression/src/**'
            hls-stats:
              - 'packages/hls-stats/src/**'
            hls-player:
              - 'packages/hls-player/src/**'
            virtual-background:
              - 'packages/hms-virtual-background/src/**'
            cypress:
              - 'cypress/**'
            build: 
              - 'scripts/**'
            ci:
              - '.github/**'
            documentation:
              - '*.(md|mdx)'

      - name: Apply or remove label
        uses: actions/github-script@v5
        env:
          CHANGES: ${{ toJSON(steps.filter.outputs) }}
        with:
          script: |
            const script = require('./scripts/labeller.js')
            await script({ github, context })
