# manadate jira number as part of the branch name
name: jira-lint
on: [pull_request]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: cleartax/jira-lint@master
        name: jira-lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://100ms.atlassian.net
          skip-branches: '^(main|production|hotfix)$'
          skip-comments: true
          pr-threshold: 1000
          validate_issue_status	: true
