name: Push to webapp
on:
  push:
    branches:
      - main

jobs:
  push-to-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote add webapp https://github.com/100mslive/100ms-web.git
          git subtree push --prefix=apps/100ms-web webapp sync-webapp
