name: check-store-size
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/hms-video-store/**'
      - '!packages/hms-video-store/cypress/**'
      - '!packages/hms-video-store/docs/**'
      - '!packages/hms-video-store/internal-docs/**'
      - '!packages/hms-video-store/images/**'
      - '!packages/hms-video-store/**/*.test.ts'

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check store size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/hms-video-store
          build_script: build:only
