name: Update publish-alpha
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: github.event.pull_request.merged == true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'dev'
          destination_branch: 'publish-alpha'
          pr_title: 'Update publish-alpha'
          pr_body: ':robot: Automated PR from dev to publish-alpha'
          pr_label: 'auto-pr'
