name: Update Sdk Version
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/hms-video-web/**'
      - '!packages/hms-video-web/cypress/**'
      - '!packages/hms-video-web/scripts/**'
      - '!packages/hms-video-web/docs/**'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get main version
        id: main
        run: |
          VERSION=$(cd packages/hms-video-web && node -p -e "require('./package.json').version")
          echo $VERSION
          echo "::set-output name=version::$(echo $VERSION)"

      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get current version
        id: branch
        run: |
          VERSION=$(cd packages/hms-video-web && node -p -e "require('./package.json').version")
          echo $VERSION
          echo "::set-output name=version::$(echo $VERSION)"

      - name: Update version
        # don't update the version if PR has a version change already, this prevents
        # overriding any manual version update by the action.
        if: steps.main.outputs.version == steps.branch.outputs.version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          cd packages/hms-video-web
          VERSION=$(npm version prerelease)
          git commit -am "build(sdk): update version to $VERSION"
          git push
