name: Update publish-alpha

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    name: Create PR from main to publish-alpha
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge main into publish-alpha"
          title: "Merge main into publish-alpha"
          body: |
            This PR merges changes from the main branch into the publish-alpha branch.
          branch: publish-alpha
          base: main
