name: Upload to S3
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'which env to deploy - qa | dev | staging | prod'
        type: 'choice'
        required: true
        default: qa
        options:
          - qa
          - dev
          - prod
          - staging
      buildEnvForDev:
        description: 'which env to build - qa/prod for dev-app, applies only if env is dev'
        type: 'choice'
        required: false
        default: prod
        options:
          - prod
          - qa
  push:
    branches:
      - main
    paths-ignore:
      - 'cypress/**'
      - 'playwright/**'
      - 'internal-docs/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_TILE_SHAPE: '1-1'
      REACT_APP_THEME: 'dark'
      REACT_APP_COLOR: '#2F80FF'
      REACT_APP_LOGO: ''
      REACT_APP_FONT: 'Roboto'
      REACT_APP_LOGROCKET_ID: ${{ secrets.LOGROCKET_ID }}
      REACT_APP_POLICY_CONFIG: ''
      REACT_APP_WEBINAR_PROPS: '{}'
      REACT_APP_DEFAULT_APP_DETAILS: '{}'
      ENABLE_ROOT_PATH_BUILD_CACHE: '1'
      REACT_APP_PUSHER_APP_KEY: ${{ secrets.PUSHER_KEY }}
      REACT_APP_AMBIENT_MUSIC: 'https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/Together+With+You.mp3'
      REACT_APP_PUSHER_AUTHENDPOINT: 'https://whiteboard-server.vercel.app/api/pusher/auth'
      REACT_APP_LOGROCKET_BLACKLIST: 'peakperformerapp.app.100ms.live,callrockethealth.app.100ms.live,buyume1.app.100ms.live,automation.app.100ms.live,juniorkoder.app.100ms.live,qaroy1.qa-app.100ms.live,kluster.app.100ms.live,pankhuriapp.app.100ms.live,leancrop.app.100ms.live,routes2roots-class.app.100ms.live,liveholofy.app.100ms.live,ulesson.app.100ms.live,truyoga.app.100ms.live'
      REACT_APP_PORTRAIT_MODE_DOMAINS: 'whatmorelive-stage.app.100ms.live,arjun.app.100ms.live,koo.app.100ms.live,socialjawn.app.100ms.live'
      REACT_APP_AUDIO_PLAYLIST: '[{"name":"Audio1","id":"audio1","metadata":{"description":"Artist1"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/audio1.mp3","type":"audio"},{"name":"Audio2","id":"audio2","metadata":{"description":"Artist2"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/audio2.mp3","type":"audio"},{"name":"Audio3","id":"audio3","metadata":{"description":"Artist3"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/audio3.mp3","type":"audio"},{"name":"Audio4","id":"audio4","metadata":{"description":"Artist4"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/audio4.mp3","type":"audio"}]'
      REACT_APP_VIDEO_PLAYLIST: '[{"name":"100ms-360P","id":"video1","metadata":{"description":"100ms"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/100ms-360p.mp4","type":"video"},{"name":"100ms-720P","id":"video2","metadata":{"description":"100ms"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/100ms-720p.mp4","type":"video"},{"name":"Big Buck Bunny","id":"video3","metadata":{"description":"Bunny"},"url":"https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/video2.mp4","type":"video"}]'
      REACT_APP_HEADLESS_JOIN: false
      REACT_APP_ENABLE_STATS_FOR_NERDS: 'true'
    steps:
      - name: log inputs
        run: |
          echo "env: ${{ github.event.inputs.env }}, branch: ${{ github.ref_name }}"

      # prod app can only be deployed to from a branch starting with production in its name
      # - name: Validate branch
      #   if: ${{ (github.event.inputs.env == 'prod') && (!startsWith(github.ref_name, 'production')) }}
      #   run: exit 1

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: yarn packages cache
        uses: actions/cache@v2
        if: github.event.inputs.env != 'prod' || github.event.inputs.env != 'staging'
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build for Dev
        if: github.event.inputs.env == 'dev'
        run: yarn build
        env:
          REACT_APP_ENV: ${{ github.event.inputs.buildEnvForDev }}

      - name: Build for QA
        if: github.event.inputs.env == 'qa' || github.ref_name == 'main'
        run: yarn build
        env:
          REACT_APP_ENV: 'qa'
          REACT_APP_ENABLE_WHITEBOARD: 'true'

      - name: Build for Production
        if: github.event.inputs.env == 'prod' || github.event.inputs.env == 'staging'
        run: yarn build
        env:
          REACT_APP_ENV: 'prod'

      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: apps/100ms-custom-app/build

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - name: Download Build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build

      - name: Upload to Dev S3 Bucket
        if: github.event.inputs.env == 'dev'
        env:
          BUCKET: ${{ secrets.S3_BUCKET_DEV }}
        # upload static folder first and then upload the rest to ensure index.html assets are all present
        run: |
          aws s3 sync ./build s3://$BUCKET --exclude "index.html"
          aws s3 sync ./build s3://$BUCKET --include "index.html"

      - name: Upload to QA S3 Bucket
        if: github.event.inputs.env == 'qa' || github.ref_name == 'main'
        env:
          BUCKET: ${{ secrets.S3_BUCKET }}
        # upload static folder first and then upload the rest to ensure index.html assets are all present
        run: |
          aws s3 sync ./build s3://$BUCKET --exclude "index.html"
          aws s3 sync ./build s3://$BUCKET --include "index.html"

      - name: Upload to Staging S3 Bucket
        if: github.event.inputs.env == 'staging' || github.event.inputs.env == 'prod'
        env:
          BUCKET: ${{ secrets.S3_BUCKET_STAGING }}
        # upload static folder first and then upload the rest to ensure index.html assets are all present
        run: |
          aws s3 sync ./build s3://$BUCKET --exclude "index.html"
          aws s3 sync ./build s3://$BUCKET --include "index.html"

  upload-prod:
    if: github.event.inputs.env == 'prod' || github.event.inputs.env == 'staging'
    environment:
      name: ProductionWithPermissions
    needs: upload
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - name: Download Build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build

      - name: Upload to Prod S3 Bucket
        env:
          BUCKET: ${{ secrets.S3_BUCKET_PROD }}
        # upload static folder first and then upload the rest to ensure index.html assets are all present
        run: |
          aws s3 sync ./build s3://$BUCKET --exclude "index.html"
          aws s3 sync ./build s3://$BUCKET --include "index.html"

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_DEPLOY_PROD_CHANNEL_ID }}
          status: Success
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_DEPLOY_PROD_CHANNEL_ID }}
          status: Failed
          color: danger
